### ISSUE TITLE
Change line length limit from 72 to 80

### ISSUE THREAD

**Issue by saad-ali** [container-storage-interface/spec#101]
https://github.com/container-storage-interface/spec/blob/master/CONTRIBUTING.md defines the following:

`This also applies to the code snippets in the markdown files. Please wrap the code at 72 characters.`

72 is an odd choice. Standard choice is 80 or 120.

I suggest switching to 80.

CC @akutz @jdef @jieyu

**Comment by jieyu** [comment]
It's not random :)
https://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting

But I am also fine with 80 :)  120 is a bit too long for my screen.

**Comment by gpaul** [comment]
The most convincing argument I have heard for a line length of <=80 is from a colleague who uses a Braille reader. Even high-end models only have 80 characters per line. Incidentally, a similar argument holds for tabs over spaces: visually impaired individuals can set the tab width in their editors to make the code easier to read.

**Comment by saad-ali** [comment]
Too late now.
