### ISSUE TITLE
spec: The CSI_ENDPOINT example may be incorrect

### ISSUE THREAD

**Issue by akutz** [container-storage-interface/spec#105]
Regarding the `CSI_ENDPOINT` [example](https://github.com/container-storage-interface/spec/blob/master/spec.md#csi_endpoint):

```
unix://path/to/unix/socket.sock
```

I believe the above should be:

```
unix:///path/to/unix/socket.sock
```

The pattern `{scheme}://{authority}{endpoint}` results in `tcp://localhost:PORT`when dealing with TCP sockets, but for UNIX sockets there should be **three** slashes when referring to a path rooted at `/`. The `//` after the `{scheme}:` does not automatically account for the root filesystem character of `/`.

**Comment by jdef** [comment]
agreed
