### ISSUE TITLE
Spec build issue in Travis-Ci

### ISSUE THREAD

**Issue by casusbelli** [container-storage-interface/spec#107]
Travis-Ci fails on pr #99 which builds fine on my machine. I can't really make out what the check is stumbling about, any hints on that?
The error report can be found at https://travis-ci.org/container-storage-interface/spec/jobs/277245464

**Comment by jdef** [comment]
What version of golang a protoc are you using to regenerate the golang
bindings?

**Comment by casusbelli** [comment]
I initially ran with golang 1.6.3 and libprotoc 2.6.1. Upon seeing the issue i upgrade to golang 1.8.3 and recompiled but the resulting files do not differ from the 1.6.3 compilation results. Maybe the libprotoc version is the culprit?

**Comment by jdef** [comment]
yes, upgrade protoc

```
$ protoc --version
libprotoc 3.3.0
```

**Comment by akutz** [comment]
Hi @jdef,

If he was running the compilation locally, it should have downloaded `protoc` at version 3.3.0 as it is designed to so in the [Makefile](https://github.com/container-storage-interface/spec/blob/master/lib/go/Makefile#L24).

**Comment by casusbelli** [comment]
@akutz Good pointer. Following up on your hint i checked and protoc 3.3.0 is indeed installed in spec/lib/go/protoc during the make build. But still the recompilation did not  change the protobuf result. I manually added the 3.3.0 binary to PATH to take precedence over the system installation binaries  and later added the spec/lib/go dir to the GOPATH but still no luck (compilation results do not differ from the submitted version). Besides running make clean / clobber in between tests i also tried  manually removing the compilation results just to make sure. Next step i can think of is removing the system packages for  libprotoc and install 3.3.0 system wide but if the make files do install a local libprotoc version this should be used, shouldn't it? I'm starting to think that the local libprotoc 3.3.0 was used all along already (me not noticing as it was not part of the general env paths but used in the local paths in the make process) and the issue lies somewhere else?
Also, I'm relying on the fact that the csi.proto file or the lib/go/csi/csi.pb.go file need to change from the currently submitted version in order to solve the CI issue, is that wrong?

**Comment by casusbelli** [comment]
Ok, found it. There were compilation artifacts in lib/go/ that weren't refreshed when recompiling and seemingly caused this. I kicked out everything but readme, Makefile and csi.go from that directory and reran the compilation, resulting in a new lib/go/csi/csi.pb.go file. This one the CI can work with.
Maybe something similiar could be added to a make clean target in /lib/go . However someone upgrading his golang installation in between is probably not that common.
Thanks for the feedback!
