### ISSUE TITLE
Spec: Clarify what happens if node is unavailable when NodeUnpublishVolume() is called.

### ISSUE THREAD

**Issue by govint** [container-storage-interface/spec#125]
If the node that had earlier responded to a NodePublishVolume() is now unavailable for some reason, the CO may end up being unable to call NodeUnpublishVolume() on that node. What happens to the volume in this case? It should be expected that the volume be made available on a different node so the workload can continue to run on another node. Something like a ControllerPreemptVolume() to allow the plugin to recover the volume from where it was published earlier may be applicable.

Also, should clarify whether its expected that the node plugin keep state of the volumes published per node in the event that a node goes down and comes back up _after volumes were published on that node_. Is it expected that the node plugins respond as expected to NodeUnpublishVolume() requests correctly after the node has come back? It should be expected of both the node and controller plugins to track state and should be mentioned so.

**Comment by saad-ali** [comment]
ControllerUnpublishVolume allows for nodeId to be empty as a signal that the volume should be removed from whatever node it is attached on. That could be used to implement this recovery behavior.
