### ISSUE TITLE
Spec plugin name (characters, max length, structure)

### ISSUE THREAD

**Issue by saad-ali** [container-storage-interface/spec#145]
The plugin name may be:
* Used in file paths.
* Passed in through CO's APIs by the user to refer to the plugin.
* Used as a "label" or "annotation" key or value.

We should specify valid plugin names such that they can be used in all of these ways.

My proposal:
  * A fully qualified "reverse DNS subdomain" (I forget what this is called), which includes the plugin's host company name and the plugin name, to minimize the possibility of collisions.
  * For example
    * com.google.storage.csi.gce-pd
    * io.kubernetes.storage.csi.flex
  * The plugin name MUST be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between.

Thoughts?

**Comment by jdef** [comment]
I'm fine w/ reverse domain name notation (
https://en.wikipedia.org/wiki/Reverse_domain_name_notation).

63 chars seems limiting, but we can start with it and maybe expand it later
if it's too restrictive.

**Comment by jdef** [comment]
related to #3

**Comment by julian-hj** [comment]
Seems good to me.

**Comment by edisonxiang** [comment]
Hi @saad-ali, @jdef , I submitted a PR about these issue. Welcome to review it. #149
