### ISSUE TITLE
Have just plugin capabilities instead of node or controller capabilities

### ISSUE THREAD

**Issue by saad-ali** [container-storage-interface/spec#159]
As a CO I would like to be able to probe either the Node or Controller deployment to discover the CSI plugin's complete set of capabilities.

`GetNodeId()`, for example, is a Node service method. It is defined in the spec as: `Node Plugin MUST implement this RPC call if the plugin has PUBLISH_UNPUBLISH_VOLUME controller capability.` However the `PUBLISH_UNPUBLISH_VOLUME` capability is a `ControllerServiceCapability`, therefore, as a CO, before calling `GetNodeId()` I have to call the controller plugin to get the capability (not possible in the k8s design) and then issue the call against the node plugin. If both the node plugin and controller plugin advertised the complete set of capabilities for the plugin, I could just probe the node plugin, and figure out if `GetNodeId()` was required or not.

**Comment by jdef** [comment]
Is this a v0.1 blocker?

**Comment by saad-ali** [comment]
Replaced with https://github.com/container-storage-interface/spec/issues/162
