### ISSUE TITLE
Change “ID” to “Id” in Method names

### ISSUE THREAD

**Issue by saad-ali** [container-storage-interface/spec#173]
Recommendation from a gRPC author after review of CSI API: follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case style guide

Specifically, `GetNodeID(...)` should be `GetNodeId(...)`

**Comment by saad-ali** [comment]
If we do this, @jieyu suggested renaming `GetNodeId()` to `NodeGetId()` for consistency with other method names in the `Node` service.

**Comment by jieyu** [comment]
xref #137 

@akutz suggested that

**Comment by pure-yesmat** [comment]
Hello,

This causes golint to fail for NodeGetId because it expects NodeGetID. Is the recommendation to ignore this error?

Should we use something like this for the go generated file:

```
you can use github.com/gogo/protobuf

message C {
	optional int64 size = 1 [(gogoproto.customname) = "MySize"];
}
type C struct {
	MySize		*int64
}
```

This is a snippet from: https://github.com/golang/protobuf/issues/156

Thanks

**Comment by jdef** [comment]
Where is golint failing, exactly? When linting your client code, or the
generated proto bindings?

**Comment by jdef** [comment]
golint should NOT be linting generated-code:
https://github.com/golang/lint/blob/c72d1a524d88a66072b772f7452bd830adf57bcd/lint.go#L125

**Comment by pure-yesmat** [comment]
The implementation of the NodeServer interface. Example:
type nodeServer struct{
}
func (ns *nodeServer) NodeGetId(...) {
}

**Comment by pure-yesmat** [comment]
Ping :)

**Comment by gpaul** [comment]
So, in your code...

**Comment by gpaul** [comment]
You're saying in order to implement the CSI spec you have to write Go code by hand that does not pass golint?

**Comment by gpaul** [comment]
I think you'll want to wait for and weigh in on https://github.com/golang/protobuf/issues/555.
