### ISSUE TITLE
Remove `VolumeCapabilites` from `GetCapacityRequest`

### ISSUE THREAD

**Issue by saad-ali** [container-storage-interface/spec#191]
GetCapacityRequest is currently defined as follows:

```PROTO
message GetCapacityRequest {
  // The API version assumed by the CO. This is a REQUIRED field.
  Version version = 1;

  // If specified, the Plugin SHALL report the capacity of the storage
  // that can be used to provision volumes that satisfy ALL of the
  // specified `volume_capabilities`. These are the same
  // `volume_capabilities` the CO will use in `CreateVolumeRequest`.
  // This field is OPTIONAL.
  repeated VolumeCapability volume_capabilities = 2;

  // If specified, the Plugin SHALL report the capacity of the storage
  // that can be used to provision volumes with the given Plugin
  // specific `parameters`. These are the same `parameters` the CO will
  // use in `CreateVolumeRequest`. This field is OPTIONAL.
  map<string, string> parameters = 3;
}

```

The purpose of `parameters` is to capture the information about what type ("class") of volume that we care about. So it makes sense in this call ("What is the capacity that I can provision for this class?")

`VolumeCapability` contains specific information about how a particular volume will be consumed (block vs file) etc. Requiring this information couples the `GetCapacity(...)` call to a specific volume instance and prevents it form being used (without a specific volume).

So, in order to allow `GetCapacity(...)` to be called independent of any specific volume request, I propose removing `VolumeCapabilites` from `GetCapacityRequest`.

CC @jdef @jieyu

**Comment by jdef** [comment]
There's almost always overhead for filesystem metadata (and possibly even
for block metadata) that could affect the reported capacity. For example,
GetCapacity could report that there's 0.97MiB available for an ext4
filesystem-based MOUNT volume and 1MiB for a BLOCK volume. It's not a huge
difference, but why would we want to hamstring the ability of a plugin to
report precise capacity information?

**Comment by saad-ali** [comment]
> It's not a huge difference, but why would we want to hamstring the ability of a plugin to
report precise capacity information?

Doing so reduces how the call can be used. Specifically we would like to be able to query for a given storage class (independent of any particular volume) what the capacity of that class is, so we won't have a `volume_capabilities`.

I realize now that `volume_capabilities` is defined as optional. So that should be sufficient to handle our use case. We would only specify `parameters` not `volume_capabilities`.

Will close this issue.
