### ISSUE TITLE
Add Snapshot Support in the CSI Spec

### ISSUE THREAD

**Issue by xing-yang** [container-storage-interface/spec#208]
Many storage systems (cloud providers and other storage backends) support the volume snapshot feature as a way to protect data stored on the persistent volumes.  In the case when the original volume gets corrupted,  a volume can be created with the data restored from the point-in-time snapshot to prevent data loss.  Currently CSI does not have support for snapshot.  This issue is raised to add snapshot functionalities in the CSI spec.

A PR is submitted here: #224

**Comment by jdef** [comment]
closing, fixed by #224
