### ISSUE TITLE
Add SELinux support

### ISSUE THREAD

**Issue by jsafrane** [container-storage-interface/spec#235]
CO (at least Kubernetes) needs to know if underlying storage volume supports SELinux or not to be able to make the volume accessible to container that runs with certain SELinux label. Typically `docker run -v <path on host>:<path in container>:Z ... ` is used to achieve that. 

Most block based volumes with a decent filesystem on it (xfs / ext3 / btrfs /  ...) do support SELinux and `:Z` will do the right thing.

Most of network filesystems (NFS, CIFS, Gluster, CephFS, ...) do not support extended attributes + SELinux and `:Z` will fail.

It's the plugin who should give CO information if the plugin itself or given volume support SELinux.

I propose either to extend `NodeGetCapabilitiesResponse` with new `SELINUX` value or add `NodeGetVolumeInfo` that returns `bool SELinux` (wrapped in a nice structure) for a given volume. The second solution allows a plugin to support SELinux only for some volumes.

**Comment by cpuguy83** [comment]
I do not believe the plugin needs to tell the CO if selinux is supported. The CO should attempt to set the selinux labels and check the errors. If the returned error is ENOTSUP then the CO should determine how to deal with that (e.g. error out, log the error and continue).

**Comment by cpuguy83** [comment]
@jsafrane This seems like a Kube issue (not to make light of it). CRI in this case should define how to deal with the error in this case. The CRI backend could just make this determination itself, but for uniformity it could be defined as part of CRI.

**Comment by jdef** [comment]
What's the workflow here? Something like...

1. CO invokes NodePublishVolume on Plugin (... results in directory that is
mounted into workload container)
2. SELinux labels are set on the newly mounted volume directory

If so, I don't understand why the CO can't continue to set SELinux labels -
why complicate the CSI spec for this?

**Comment by jsafrane** [comment]
> 1. CO invokes NodePublishVolume on Plugin (... results in directory that is mounted into workload container)

It's not mounted into workload container, it's mounted on the host. The workload container is started *after* `NodePublishVolume`. Data on the volume must be relabeled with the right SELinux label if the volume supports that during container startup (i.e. before container main process starts).

**Comment by jdef** [comment]
Thanks for clarifying, Jan. Even so, it sounds like the CO *could* happily
continue to set SELinux labels w/o assistance from CSI.

What's the benefit of pushing something like this into CSI? Simply to
relieve the CO of complexity that it currently deals with? Or is there a
desire for uniform behavior across CO's w/ respect to SELinux-labeling?
This seems loosely related to previous discussions we've had about
representing user identity across COs -- except that in this case the
concept of a "SELinux label" is pretty clearly defined and unlikely to be
misinterpreted. That said, is it worth implementing the re-labeling logic
across 50 plugins, vs 4 CO implementations? One of the goals of CSI was to
reduce the burden of plugin writers. Keeping plugins relieved of the burden
of applying SELinux labels feels like aiming in the right direction.

**Comment by jsafrane** [comment]
User IDs is great example. CO typically runs workload containers under UID != 0. If this container needs a volume, CO uses CSI NodePublish to mount it somewhere on the host. CSI plugin does not know anything about container UIDs (and IMO that's right) and typically runs simple `mkfs.ext4` to format a provisioned volume. This results in `rwxr-xr-x` permissions on the root of the volume. CO then needs to make the data on the volume available to the UID that the container has. Kubernetes has some options, some of them result in `chown` on all data on the volume.

SELinux is exactly the same. `mkfs` does not label the volume and CO must make sure that the data have the right label so workload container can access it.

We can be reasonably sure that all CSi plugins support some subset of POSIX, especially UIDs, so CO can `chown()` files on the volumes. It's not so clear with SELinux - some filesystems support it, some don't. Only plugin knows.
I'll check if there is a safe way for CO to probe this, my gut feeling is that it's going to be error prone.

There is no need for any CSI plugin to support any relabeling, all I need is a simple bool if the plugin (or specific volume?) supports SELinux. I agree that the relabeling logic must be in CO (or the container runtime it uses).

**Comment by jsafrane** [comment]
I dug deeper into SELinux internals and it seems that `seclabel` appears in mount options in /proc/mounts if the volume supports SELinux. So we don't need CSI to report anything, I'll solve it on Kubernetes side.
