### ISSUE TITLE
Storage: object type what describes the storage cluster

### ISSUE THREAD

**Issue by rudyfly** [container-storage-interface/spec#239]
In CSI spec, it has no storage object type what describes the storage cluster information, such as cluster address, credentials, key and so on.
Why do this. In my case, node server supports multiple storage cluster to access, so storage information can't store on node server, it should be passed by calling `NodeStageVolume/NodePublishVolume` interface, it can be included in volume struct. It means this volume that has been created in specify storage cluster.
Although `Volume` has extended parameters, but I think it is not reasonable to contain storage information by extended parameters.

**Comment by jdef** [comment]
At volume-create time you can specify opaque parameters in the
CreateVolumeRequest. The resulting volume MAY contain additional opaque
information in the form of attributes. There are other, specific fields in
certain CSI RPC messages for credentials/secrets.

It's not entirely clear to me how the fields already offered by the spec
don't address your use case. Would you mind providing a step-by-step
walkthough of how you intend to use the CSI RPCs and where they fall short?

**Comment by saad-ali** [comment]
Agreed with @jdef. This is what opaque parameters are for in CreateVolumeRequest.
