### ISSUE TITLE
Response of the `DeleteVolume` for an invalid volume ID?

### ISSUE THREAD

**Issue by arm64b** [container-storage-interface/spec#249]
> This operation MUST be idempotent. If a volume corresponding to the specified volume_id does not exist or the artifacts associated with the volume do not exist anymore, the Plugin MUST reply 0 OK.

Can't understand the rational here why the **Plugin MUST reply 0 OK** in case of the volume specified by the `volume_id` doesn't exist, I think it should reply an error code to notify the peer the delete operation doesn't succeed. (?) @saad-ali @jieyu

**Comment by jdef** [comment]
Let's suppose that the spec was amended to return an error code for a
DeleteVolume request that references a vol that does not exist. Upon
receiving such an error code, how would the CO react any differently than
if it had received a "0 OK"?

**Comment by arm64b** [comment]
IMO the CO should return an error code/msg or whatever to the end user that the operation doesn't succeed while not fake a illusion for the user that the `delete` is OK.
Let's see some code example:

https://github.com/kubernetes-csi/external-provisioner/blob/master/vendor/github.com/container-storage-interface/spec/lib/go/csi/v0/csi.pb.go#L2037

https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/storageos/storageos.go#L552

Since all those codes above will return `error` for the `DeleteVolume`, so I think the CO should have a consistent error handling mechanism for that, am I missing something here?   

> Let's suppose that the spec was amended to return an error code for a
DeleteVolume request that references a vol that does not exist. Upon
receiving such an error code, how would the CO react any differently than
if it had received a "0 OK"?

**Comment by saad-ali** [comment]
> IMO the CO should return an error code/msg or whatever to the end user that the operation doesn't succeed while not fake a illusion for the user that the delete is OK.

The CO in this case does not return single operation information to the end user. The CO is responsible for eventual consistency. As long as the state of the storage system is what the CO expects, it is happy. In this case as long as the volume no longer exists, the CO is happy. The user does not need to be bothered with that info.

**Comment by cpuguy83** [comment]
Generally agree with @saad-ali, however in terms of debug-ability, it might be nice to have this information in the CO if for nothing else then a tracing/logging. Just a thought.
