### ISSUE TITLE
Consider having controller-only plugins with node plugin backends

### ISSUE THREAD

**Issue by gman0** [container-storage-interface/spec#263]
This proposal is intended to open a discussion about the feasibility of having controller-only plugins that can instruct the CO which node plugin should be used for attaching/mounting the provisioned volume on workloads.

The main use-cases for this are OpenStack's Manila and Cinder services, but any such scenario where a single Controller Plugin acts as a multiplexer and is able to provision volumes of multiple kinds could benefit from this.

I'll describe the scenario with Manila: the Manila service can provision shared file-systems for CephFS, HDFS, GlusterFS, NetApp, etc. There are specialized CSI plugins for (at least, at the moment) CephFS, NetApp storage. The idea is to accommodate a Controller-only plugin (i.e. the "multiplexer") which would only provision the volume + **instruct the CO which Node plugin** (i.e. the "backend") should be used when placing the volume to workload, granted all the necessary volume attributes and secrets are in place. This is as opposed to what e.g. csi-cinder is doing which does both provisioning multiple kinds of block-storage and attaching&mounting on its own - I'd say reusing already existing plugins that deal with a specific FS is cleaner than dealing with everything in one place.

Plugin name is a well-established entity in Identity Service so this should be ok as an identifier, and I'm guessing at some point each CO has to decide where to route the Node Service RPCs. This is the place where the plugin name from Controller plugin could be injected. A new optional field `node_plugin_name` could be added to `CreateVolumeResponse` which, if non-empty, must contain a valid Identity Service's plugin name, and it instructs the CO which Node plugin shall be used for this volume. If left empty, the behavior stays the same as it is now.

@jdef @saad-ali

**Comment by jdef** [comment]
It sounds like something that is doable w/o changing the CSI specification. for example, consider the following arch:
![alternative text](http://www.plantuml.com/plantuml/proxy?src=https://gist.githubusercontent.com/jdef/1e182544d5e09db69ba07f61478c4331/raw/8815dea58e4b7e24ded6cc1bad5641747243f69b/csi-multiplexing-controller-proxy.uml)

1. The `[M]` plugin complements are the multiplexing/proxy layer. The `[S]` plugin components are the slave, node-only plugins. The CO issues calls to the multiplexer/proxy plugin only.
1. Invocations of Node RPCs are forwarded to the appropriate slave. The spec already provides a mechanism for opaque metadata to be passed from Controller RPC responses to Node RPC requests - there is no need to first class additional fields (like `node_plugin_name`).
1. CSI already halfheartedly supports node-only plugins.
1. CSI doesn't call out the above architecture as a "common" reference arch; that doesn't mean that it's off limits.

**Comment by gman0** [comment]
Thank you! This looks really good, I wasn't aware forwarding RPCs in such manner is allowed.

Still - in regards to passing data around, there's an asymmetry in CSI where plugins can pass non-sensitive data (metadata), but the spec leaves no way to pass sensitive data (secrets). I guess we can continue in #261.

**Comment by gman0** [comment]
@jdef I'm closing this issue as your response solved this topic. Thanks again.

**Comment by jdef** [comment]
The spec doesn't have an opinion re: RPC forwarding. AFAIK the initial rexray implementation could proxy CSI gRPC calls to backend "slave" plugins.
