### ISSUE TITLE
How to load secrets into CO

### ISSUE THREAD

**Issue by haizaar** [container-storage-interface/spec#264]
I'm reviewing the CSI spec and it's clear that many RPCs accepts credentials to be used for communication with storage providers. However it's not clear how to load these credentials into CO and associate them with a particular CSI plugin.

E.g. In case of K8s, we can create secrets object that will contain the credentials, but how to tell K8s to use this particular secrets object together with my CSI plugin?

**Comment by jdef** [comment]
This sounds like a question for the k8s storage SIG, not the CSI community
in general.

**Comment by haizaar** [comment]
Makes sense. Opened a discussion: https://groups.google.com/forum/#!topic/kubernetes-sig-storage/cLDeFBPrGL0

Thank for the hint.
