### ISSUE TITLE
Repackage generated lib/go/csi/... stubs for compat w/ go modules 

### ISSUE THREAD

**Issue by jdef** [container-storage-interface/spec#273]
golang modules disallow v0 and v1 from import paths:
* https://github.com/golang/go/wiki/Modules#why-are-major-versions-v0-v1-omitted-from-import-paths

**Comment by saad-ali** [comment]
Action item: 
  * P0 - Remove v0 from path.
  * P2 - Document breaking changes should go in v2 subdirectory
