### ISSUE TITLE
Clarify ordering of volumes ops to controller plugin

### ISSUE THREAD

**Issue by govint** [container-storage-interface/spec#28]
The sections for delete-volume, publish/unpublish-volume calls to the controller plugin need to be updated  to say that the CO will ensure it takes responsibility to call a volume delete-op on the controller plugin _after_ all users on all nodes have been confirmed to have stopped.

Like if a volume is published to node N, it's the CO's responsibility to ensure the volume is unpublished before calling a DeleteVolume. At least update the spec to say what are the CO's and SP's responsibilities with regards to keeping tabs on volumes in use when a delete is attempted on those.

**Comment by jdef** [comment]
Perhaps we could, minimally, add an error code for `DeleteVolume` that indicates it should be unpublished before being deleted?

This seems related to the use case of reporting the nodes to which a volume is attached (#5) so that a CO can reconcile its state with that of the plugin's.

**Comment by julian-hj** [comment]
+1 on this issue.  If one of our goals is to enable plugins to be fully stateless, then the plugin may not have any clue whether or not there are attachments.  So it would make sense to me that the CO ought to be responsible for bookkeeping about existing attachments and also for making a best effort to detach before deleting.

**Comment by saad-ali** [comment]
DeleteVolume error codes define https://github.com/container-storage-interface/spec/blob/master/spec.md#deletevolume-errors

```
Volume In Use

Caller SHOULD ensure that there are no other resources using the volume, and then retry with exponential back off.
```

And there is a state diagram at the top. I think that should be sufficient.
