### ISSUE TITLE
NodePublishVolumeRequest() should define what to do as a driver when given a targetPath for a block volume

### ISSUE THREAD

**Issue by lpabon** [container-storage-interface/spec#287]
NodePublishVolumeRequest() should define what to do as a driver when given a targetPath for a block volume. Right now in Kubernetes-csi we are assuming it is the responsibility of the CO to create the directory where the Symlink will live, for the CO to pass the targetPath (which is the symlink name) and for the CO to create the symlink to the raw device node.

See #285

**Comment by jieyu** [comment]
We need to make it clear in the spec that who (CO or SP) is responsible for creating the target_path, and the target_path will be a file for block device and a directory for volume.

**Comment by jieyu** [comment]
This is related to #80

**Comment by saad-ali** [comment]
Resolved in #335
