### ISSUE TITLE
Decorate fields with sensitive data

### ISSUE THREAD

**Issue by saad-ali** [container-storage-interface/spec#291]
Let's consider decorating fields that could contain sensitive data, e.g. secrets, mount flags, etc. in a way that would allow programmaticly excluding the field from logging over the wire.

I believe google may have a proto extension for this, will need to dig around.

**Comment by saad-ali** [comment]
At a very minimum, on the fields that have sensitive data, we should have a comment on that field (not some where else in the spec) saying it may contain sensitive data and should (must?) not be logged.

**Comment by jdef** [comment]
https://github.com/container-storage-interface/spec/pull/233 ?

**Comment by saad-ali** [comment]
Yes!!

https://developers.google.com/protocol-buffers/docs/proto#customoptions

**Comment by saad-ali** [comment]
Closed with https://github.com/container-storage-interface/spec/pull/317
