### ISSUE TITLE
Clarify VolumeID name-spacing requirements

### ISSUE THREAD

**Issue by saad-ali** [container-storage-interface/spec#300]
A volume or node ID returned by one CSI driver may collide with a volume or node ID from another driver.

Spec should clarify that it is the responsibility of the CO to ensure that it does appropriate namespacing to handle such collisions.

**Comment by jdef** [comment]
Why is it the responsibility of the SP? Because that keeps things simpler for the CO?

**Comment by saad-ali** [comment]
> Why is it the responsibility of the SP? Because that keeps things simpler for the CO?

Whoops that should say CO not SP, fixed.

**Comment by saad-ali** [comment]
Recommendation from @jdef and @julian-hj : `x is unique per driver, the plugin is NOT responsible for global uniqueness  `

**Comment by saad-ali** [comment]
Closed with #318
