### ISSUE TITLE
Consider replacing SnapshotStatus enum with booleans

### ISSUE THREAD

**Issue by saad-ali** [container-storage-interface/spec#302]
An enum when used for "state" encourages clients to write switch statements or or statements capturing every currently known state of enum and fail if the state is unrecognized. This leads to clients breaking when a new value is added to the enum (which should be a non-breaking additive change). 

In Kubernetes we've moved to a model where we flaten the enum in to booleans, e.g. `is_ready`, which makes it harder for a client to be written in a forward incompatible way.

So request is to consider replacing SnapshotStatus enum with booleans.

**Comment by saad-ali** [comment]
@julian-hj made a good point: Kubernetes has to deal with many many consumers, this code is consumed by a handful of COs, so this is not as much of an issue.

Also @jdef mentioned that for terminal states, you would want the client to fail so optimizing for non-terminal states doesn't necessarily add much value.

Agreed with both points, will close this issue.

**Comment by saad-ali** [comment]
> Also @jdef mentioned that for terminal states, you would want the client to fail so optimizing for non-terminal states doesn't necessarily add much value.

Discussed this some more with thockin. He pointed out that a good APIs should not make backwards compatibility breaking changes but may make additive changes. And when you have additive changes a list of booleans is much less likely to cause breakages then an enum (e.g. introducing a new state that new clients should handle, but doesn't invalidate any existing state or any existing clients handling of that state).

I'll leave this open for now. If we can't get consensus on it by the time we want to cut 1.0.rc we can abandon it. In the meantime assigning to @xing-yang @jingxu97 to explore.

**Comment by jdef** [comment]
At first glance I think that sounds OK to me.

**Comment by julian-hj** [comment]
Sounds good to me.  It would bring the snapshot RPCs more in alignment with the other RPCs.
