### ISSUE TITLE
GetNodeIDErrorCode needs help

### ISSUE THREAD

**Issue by jdef** [container-storage-interface/spec#31]
#21 adds `GetNodeIDError` to the possibilities of an `Error.value`, but the codes defined by `GetNodeIDErrorCode` don't actually seem to apply to `GetNodeID` -- copy/paste error?

**Comment by akutz** [comment]
Hi @jdef,

This is blocking my work as I cannot respond to a `GetNodeID` request with an appropriate error.

**Comment by akutz** [comment]
Also, this has been outstanding for 27 days. May I recommend you bring some additional people onto the project to take a more active role in reviewing and fixing issues? I volunteer :)

**Comment by akutz** [comment]
FWIW I've resolved it locally with my [`csi.mk` file](https://gist.github.com/akutz/2b0126749b00b53294314557310aae52#file-csi-mk). The relevant section is [lines 140-152](https://gist.github.com/akutz/2b0126749b00b53294314557310aae52#file-csi-mk-L140-L152):

```make
$(CSI_PROTO):
	@mkdir -p $(@D)
	ref=$$(git ls-remote $(CSI_GIT_URI) $(CSI_GIT_REF) | awk '{print $$1}') && \
	ref="$${ref:-$(CSI_GIT_REF)}" && \
	printf "$(CSI_PRINTF_FMT)" \
	  "$(CSI_GIT_OWNER)/$(CSI_GIT_REPO):$${ref}" \
	  "$(CSI_IMPORT_PATH)" \
	  "$(CSI_IMPORT_PATH)" > $@ && \
	curl -sSL $(CSI_SPEC_URI) | \
	sed -n -e '/```protobuf$$/,/```$$/ p' | \
	sed -e 's@^```.*$$@////////@g' \
	    -e 's@\(ProbeNodeError probe_node_error = 9;$$\)@\1\
    GetNodeIDError get_node_id_error = 10;@g' >> $@
```

**Comment by jdef** [comment]
Thanks for the bump, I'll prioritize this

**Comment by jdef** [comment]
@akutz PR #21 has landed, hopefully this unblocks you

**Comment by jdef** [comment]
pretty sure that #115 resolved this. if not, please re-open
