### ISSUE TITLE
Change all instances of v0.x in spec in prep for 1.0

### ISSUE THREAD

**Issue by saad-ali** [container-storage-interface/spec#319]
For example:

```
package csi.v0;
```
and
```
The Container Storage Interface (CSI) explicitly will not define, provide, or dictate in v0.1:
```

**Comment by jdef** [comment]
We probably want to leave a version in the proto package name because not
all langs have the same kind of flexibility as golang.

**Comment by jieyu** [comment]
I think he meant to change from v0 to v1
