### ISSUE TITLE
spec: Snapshot.created_at should use well-known Timestamp protobuf

### ISSUE THREAD

**Issue by jdef** [container-storage-interface/spec#330]
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto

This would be a breaking change after 1.0, so if this change doesn't land before then maybe we could eventually use a `oneof` to wrap the existing int-based timestamp and a new field that uses `Timestamp`.

Ideally we'd resolve this prior to 1.0

**Comment by saad-ali** [comment]
I support this change.
