### ISSUE TITLE
Need a status polling mechanism for Volume/Snapshot create/delete

### ISSUE THREAD

**Issue by rootfs** [container-storage-interface/spec#34]
Volume and snapshot (mostly snapshot) create/delete could be lengthy process. As exhibited in AWS EBS [API](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSnapshot.html), the return status is not binary true or false; it contains a status  that callers can issue subsequent request to poll the latest status of the volume/snapshot.

@jieyu @saad-ali

**Comment by jieyu** [comment]
#39
