### ISSUE TITLE
Update Drivers page

### ISSUE THREAD

**Issue by eyalglobal** [container-storage-interface/spec#348]
Please update in the CSI Drivers page (https://kubernetes-csi.github.io/docs/Drivers.html)

ScaleIO | v0.1.0 | A Container Storage Interface (CSI) Storage Plugin for DellEMC ScaleIO

to

ScaleIO | v0.1.0 (Tech Preview)| A Container Storage Interface (CSI) Storage Plugin for DellEMC ScaleIO

This is temporary, until we make the new VxFlex OS CSI  driver available.

Regards,

Eyal S.
VxFlex OS Dell EMC

**Comment by jdef** [comment]
It looks like the docs page you're referencing is for a different project.
Please post an issue against that project instead of this one.

**Comment by pohly** [comment]
Please file a PR against https://github.com/kubernetes-csi/docs with that proposed change.
