### ISSUE TITLE
Proposal: Functionality to support node failure scenarios

### ISSUE THREAD

**Issue by clintkitson** [container-storage-interface/spec#36]
Applications that require persistence likely rely heavily on the external storage volumes that CSI enables. But node failures with storage are more complex than dealing with non-persistent applications. With persistent applications, a node may fail but the data must be able to follow the application on whichever node a container gets launched. Node failures can occur for any number of reasons:
- Loss of power
- Reboots
- Kernel panics
- Network failures
- CO agent stops responding (containers running still)

CO's already have the responsibility of managing the containers themselves during scenarios like this. When persistent volumes are involved, right now the CO may not have the ability to recover without specific functionality through CSI.

For example, if a CO agent stops responding, the CO may decide to reschedule containers elsewhere. This would likely start with a `controller unpublish`, but this process can hang on its own or fail in certain scenarios. For example, with AWS EBS volumes a volume detach call will inherently respect OS level mounts of volume until unmounted. If an unmount at the node level doesn't occur, then the only method to centrally detach the volume is to do a forced detach. If the instance is powered off, then AWS will detach without issue.

Specific to this scenario, a proposal could be to include a parameter on `controller unpublish` that ensures a CO can decide when to make ungraceful calls for detach. This can be called predictably for certain scenarios, or after timeouts using the normal `unpublish` method.

I believe that operator intervention in these failure scenarios should not be needed.

**Comment by jdef** [comment]
Thanks for the suggestion!

This came up several times and a "force_detach" option was eventually
removed from the spec, mostly on the basis that there's "no safe way"
(preventing data loss) for a CO to use that option without admin
involvement. Some cloud providers implement safety checks, others do not.
If a volume operation is hung on the backend, the CO has few ways to reason
about that.

What **is** in the spec is an option that allows an Unpublish operation to
specify an empty NodeID: this could be used as a fallback in scenarios
which the CO doesn't know which Node the volume is attached to, and the CO
needs to detach it before re-attaching somewhere else. It's not exactly the
same as a "force-detach" option, but it feels like some kind of
middle-ground.

If you feel strongly that force-detach is a needed thing, can you provide
some example workflows in which it's **safe** for a CO to specify such a
flag, especially in the case of a clould/storage provider that doesn't
provide a safety-net of mount-pre-checks?

**Comment by clintkitson** [comment]
Thanks for the quick response. 

Can you expand on how the CO can handle hung volume operations? The option to specify a blank NodeID would need to be implemented as so by a CO and the plugin would need to know this infers a forced detach to make this useful wouldn't it? As part of CSI my hope is that we would enable better interactions versus making assumptions that CO/plugins can possibly interact for certain scenarios. So I'm not sure I agree its a middle ground unless I am misunderstanding. I think a forced detach is something that should be requested since it can cause data loss, and not something that occurs upon plugin decision.

What does a safety-net of mount pre-checks mean? Should I interpret this at detach pre-checks like AWS where it verifies a mount is not in place for a device? Storage platforms don't do mount pre-checks, their demarcation is typically after an attach occurs.

**Comment by jdef** [comment]
There's nothing "forced" about the empty NodeID. One of the motivations for
adding it was this: if the CO goes "crazy" and loses track of state (like
which vols are attached where) then this provides the CO with a way to
"reset" and detach from anywhere. If a plugin could implement force-detach
safely, then it **could** possibly execute such an operation in this
scenario. But empty NodeID does not imply force-detach for plugins: it
implies "make a best effort to safely detach this vol from wherever it's
currently attached".

Using "middle ground" was probably confusing, sorry.

My "safety-net" was referring to the AWS checks that you mentioned earlier,
along the lines of NOT detaching if there were any mounts on the node.
Again, apologies for the confusing terminology.

**Comment by saad-ali** [comment]
`ControllerUnpublishVolumeRequest.node_id` can now be empty to indicate the CO wants to detach from "where ever the volume is currently attached" as a way to clean it. A plugin can choose to implement this as force detach if they support it. That should be sufficient. Please reopen if you disagree.
