### ISSUE TITLE
Clarify NOT_FOUND returned from ControllerUnpublishVolumeRequest

### ISSUE THREAD

**Issue by jsafrane** [container-storage-interface/spec#373]
The spec says that `NOT_FOUND` means that a volume (or node) corresponding to the specified `volume_id` (`node_id`) does not exist.

But it does not say what does it mean to CO. When CO is sure that it sent the right IDs and something else must have deleted the volume or node, can CO assume that the volume was detached from the node automatically by SP when the volume/node was deleted? In this case, returning `OK` would have the same meaning - the volume has been unpublished and CO does not need to do anything.

CO has no way how to check / fix attachment of deleted volumes (or nodes), so it cannot do any cleanup when `NOT_FOUND` is returned.

**Comment by msau42** [comment]
NOT_FOUND handling is more relevant to Unpublish right?

**Comment by davidz627** [comment]
Are you suggesting that the `SP` should decide (based on behavior of the storage system) whether the node or volume being deleted means:
1) The volume/node is assumed to be detached - return `OK`
2) The volume/node may not be detached - return `NOT_FOUND` - `CO` has no remedying solution besides retrying (?)

**Comment by jsafrane** [comment]
Yeah, sorry, I meant Unpublish

**Comment by saad-ali** [comment]
Discussed at community meeting. Notes [here](https://docs.google.com/document/d/1-oiNg5V_GtS_JBAEViVBhZ3BYVFlbSz70hreyaD7c5Y/edit#heading=h.z24362cngqjs).

Conclusion: seems like a good idea. Clarify backwards compatibility plan. And then feel free to open PR. Would need to put prominent release note when this goes out.
