### ISSUE TITLE
Ability to enforce granular resource limits on CreateVolumeRequest

### ISSUE THREAD

**Issue by Jgoldick** [container-storage-interface/spec#42]
While perhaps out of scope, the CO should not need to know that there are storage resource limits based on admin identity or any other policy beyond of cluster-wide shared resources. In order to apply resource quotas at the Controller Plugin level there should be provision for passing the owning identity associated with a Volume. The identity of the creating admin could probably be used but it's not clear to me that this security context is supplied by the gRPC workflow from CO to the Controller Plugin.

This also implies a potential new error code for CreateVolumeRequest to describe a resource quota limit being exceeded.

**Comment by jdef** [comment]
Related to Quota (#9) and Principal (#30)

**Comment by saad-ali** [comment]
https://github.com/container-storage-interface/spec/issues/17#issuecomment-322650473
We have secrets per RPC that a plugin can used by CO to pass identity information. That can be used to implement a per identity quota.
