### ISSUE TITLE
CreateVolumeRequest - support for limited storage topology/connectivity deployments

### ISSUE THREAD

**Issue by Jgoldick** [container-storage-interface/spec#43]
Not all storage is necessarily reachable/zoned for every node, and not every node is capable of hosting every container. It would seem to be necessary to ensure that a set of nodes (all, a specific NodeId, or a tagged group of NodeId(s)) will be able to reach a new volume before issuing the CreateVolumeRequest. CO(s) often know about node-level fault domains but this is somewhat different as it's a storage connectivity level decision. Could perhaps leverage some of the concepts in [https://github.com/container-storage-interface/spec/issues/7](url) to define the groups. Note that this information might need to be a part of CreateVolumeResponse so we could handle the case where the request specified nothing but the CO still needs to know what nodes are actually capable of mounting a volume.

**Comment by cpuguy83** [comment]
I don't think the CO would know what node the workload would be scheduled to at the time of `CreateVolumeRequest`.
In terms of signaling to the backing store where in the topology the new storage should go, this is rough and likely (IMO) too much to tackle for the v1 spec. However the plugin could specify it's own set of options for where in the cluster the storage should go and the operator can pass that down.

When it comes time to schedule the actual workload the CO will call the `ControllerPublishVolume` endpoint with the node ID to attach to.
I do not believe there is currently any way for the scheduler to filter nodes based on knowledge from the plugin about where the underlying storage can be made available.

Maybe `VolumeInfo` could have a candidate node list that can be used to feed the scheduler? Alternatively something like a `ControllerGetNodeList(VolumeInfo)` could also work.

**Comment by Jgoldick** [comment]
Here's the situation I'm trying to avoid as it happened in OpenStack early on. The spec should not **implicitly** only support a homogeneous hardware/software setup for all nodes including storage. If we want to be explicit about that limitation for V1 then the rules can be made clear. For example, we would require that every node have the potential for read/write access to every Volume.

On your point about the CO not knowing what node will eventually get the workload, I think that's dependent on the CO. I'd also point out that if a Volume is only accessible from a subset of nodes then the CO has implicitly chosen where the workload can ever be placed. Take the extreme example of a Volume that is only writable by a single node, clearly the workload can never leave that node. 

In the OpenStack world we often had to zone storage such that every node in the cluster had the rights to access any Volume, and update that as cluster membership changed dynamically. If we want that to be the V1 requirement I would suggest we make it explicit.

**Comment by jdef** [comment]
In terms of API this sounds, perhaps, like a cross between domain (#7) and node capabilities? In other words a node could report which domains it's capable of publishing volumes for. We really need to flesh out what `Domain` means and how it should be used within the context of CSI

**Comment by jdef** [comment]
> I don't think the CO would know what node the workload would be scheduled to at the time of CreateVolumeRequest.

That's not always true: dynamically managed local storage is definitely tied to a particular node.

> In terms of signaling to the backing store where in the topology the new storage should go, this is rough and likely (IMO) too much to tackle for the v1 spec.

#44 captures the intent of indirectly signaling where newly allocated storage should/should-not go via so-called volume affinity/anti-affinity; perhaps this would NOT require a CO to understand intricate fault domains built into the backend storage system.

> I do not believe there is currently any way for the scheduler to filter nodes based on knowledge from the plugin about where the underlying storage can be made available.

... and this gets to the crux of this ticket AFAICT. To which I think there are a couple of low-FI solutions:

1. Don't install/run the plugin for storage X on node Y if node Y doesn't support connectivity to X, or;
1. Install all plugins everywhere, but the `ProbeNode` call for plugin for X on node Y **fails** because it's missing some connectivity requirement (driver, network configuration, etc).

`ProbeNode` is not meant to be a general purpose "health-check", and as such it's not intended to be invoked frequently (whatever that means). If the connectivity between nodes and storage backends is expected to fluctuate quickly then `ProbeNode` is probably less than ideal.

My interpretation is that this ticket is more talking about "connectivity" or "reachability" (topology) vs something like "node X is authorized to access volume Y" (security).

**Comment by jfremy** [comment]
I can see two aspects. 
1 Telling the storage back-end in which connectivity domain you want your storage to be (if you have specific needs, but it's in no way mandatory, you could just take anything)
2 Figuring out at scheduling time if a volume can be connected to a specific host

For 1, I think that you cannot avoid back-end specific parameters that can be used by the user to force a given connectivity domain. The odds that a one size fits all structure can be defined seem unlikely (but I might be wrong).
For 2, I think the scheduler should rely on a plugin call to know if a volume can be connected to a node (or from a list of nodes, return those who can connect to a group of volumes to make it more "efficient").

In our case (DriveScale), we have a lot of "connectivity" domains and by default we'd like the user not to have to care about that (though he can choose one specific domain if he wishes so).
When it comes to scheduling, then as mentioned, there could be specific annotations on the volumes and nodes that could be used by the scheduler to know what can go where but those annotations need to be kept in sync (can change over time) and that also assumes that the connectivity can be figured out based only on simple data structures. I feel it's simpler if the plugin has the responsibility to answer that question and use any arbitrary business logic needed to answer that question.

That would work fine for local storage (only return true if the node is the one that is hosting the data) and any other volume provider.
