### ISSUE TITLE
Attachment reconciling capability can only be enabled for In-Tree CSI drivers?

### ISSUE THREAD

**Issue by david-enli** [container-storage-interface/spec#442]
Hello, I apologize it this isn't the right place. After enabling `csi.ControllerServiceCapability_RPC_LIST_VOLUMES_PUBLISHED_NODES` and including the `PublishedNodeIDs ` field in the ListVolumes response. We started to see the following log message from the csi-attacher sidecar. And I found the following function called as part of the reconciling code from the sidecar: 
```
// RepairVolumeHandle generates a correct volume handle based on node ID information.
func (CSITranslator) RepairVolumeHandle(driverName, volumeHandle, nodeID string) (string, error) {
	if plugin, ok := inTreePlugins[driverName]; ok {
		return plugin.RepairVolumeHandle(volumeHandle, nodeID)
	}
	return "", fmt.Errorf("could not find In-Tree driver name for CSI plugin %v", driverName)
}
```
is reconciling not supported for non in-tree CSI drivers?  thanks in Advance for your help

**Comment by gnufied** [comment]
Please open this against `kubernetes-csi/external-attacher`. Issues like these don't belong to spec.

**Comment by david-enli** [comment]
will do, sorry about that, thanks
