### ISSUE TITLE
Secrets in NodeExpandVolume

### ISSUE THREAD

**Issue by Sh4d1** [container-storage-interface/spec#445]
Hello!

It would be nice to have secrets available in the NodeExpandVolume.

Usecase : encrypted device with LUKS, which needs the passphrase in order to resize the device on the node.

**Comment by humblec** [comment]
Indeed , this is a requirement for other use case too. For example, if we need to connect to backend cluster for some validation we need the secret. 

One of the use case came up Ceph side is that, at times we need to check the actual size of the image before proceeding on FS resize to avoid false positive returns on fs resize operation. For that we have to connect to the backend cluster which need secret in the request.

**Comment by Sh4d1** [comment]
Not sure what the policy is, but I'll gladly open a PR adding secrets to this method 😄

**Comment by humblec** [comment]
> Not sure what the policy is, but I'll gladly open a PR adding secrets to this method smile

Let me invite some key members for their thought from Kube storage side.
 @saad-ali @jsafrane @msau42 @gnufied @xing-yang can you share your thoughts ?

**Comment by humblec** [comment]
@gnufied @jsafrane @xing-yang @msau42 @saad-ali  this is one of the blocker to support LUKS encryption expansion for CSI drivers. We indeed need secrets/credentials in the NodeExpand request. Can we share your thoughts ?

@Sh4d1 would you like to open a PR for this?

**Comment by Sh4d1** [comment]
@humblec yep :smile:

**Comment by humblec** [comment]
> @humblec yep smile

Thanks @Sh4d1 ! Let me pull others to the PR :+1:
