### ISSUE TITLE
ControllerPublishVolume - Support for limited storage topology/connectivity deployments

### ISSUE THREAD

**Issue by Jgoldick** [container-storage-interface/spec#45]
There is an assumption here that the CO will not send a ControllerPublishVolume request for a NodeId that doesn't have the ability to mount the associated volume. However, without a discovery API or tagging system for topology this looks like a random discovery process. This is related to [https://github.com/container-storage-interface/spec/issues/43](url)

This could be addressed by a new connectivity discovery API or perhaps by the Plugin returning a new error code with an associated list of NodeId(s) that are acceptable candidates for a retry in the response to ControllerPublishVolume.

**Comment by saad-ali** [comment]
I believe this is addressed by https://github.com/container-storage-interface/spec/pull/188
