### ISSUE TITLE
CSI compatibility with Openshift container platform

### ISSUE THREAD

**Issue by tushar1701** [container-storage-interface/spec#450]
I need clarification and want to know about the compatibility of openshift container platform with Container storage interface. If there is any documentation stating its usage vs Kubernetes then do share that would of great help.

**Comment by tushar1701** [comment]
@saad-ali @xing-yang @jsafrane your thoughts on this please.

**Comment by xing-yang** [comment]
My understanding is that OpenShift is a distro of Kubernetes. So if an OpenShift version supports a particular Kubernetes version, then it should also support the CSI spec versions supported by that Kubernetes version.

@jsafrane or @gnufied would know the answer to this question.

**Comment by gnufied** [comment]
Yes Openshift fully supports since OCP-4.2. Also not sure if this question belongs here, such questions should be opened as openshift bug or in https://github.com/openshift/origin/

**Comment by tushar1701** [comment]
Thanks @xing-yang  @gnufied .
