### ISSUE TITLE
ControllerListVolumes - Define the initial value for starting_token

### ISSUE THREAD

**Issue by Jgoldick** [container-storage-interface/spec#47]
The spec does not indicate whether a new enumeration should just omit this field or set it to an empty string.

**Comment by jdef** [comment]
There's some ambiguity in the spec here with regard to unset proto3 "primitive" fields. Apparently it can be hard to tell the difference between an unset primitive and "zero-value" of the field. There are several places in the spec where we need to tighten this up. See #22

**Comment by saad-ali** [comment]
This has been resolved.
