### ISSUE TITLE
Go 1.10.4 build fails with undef imports in http2 pkg

### ISSUE THREAD

**Issue by chrishenzie** [container-storage-interface/spec#481]
Recent Travis CI builds for Go 1.10.4 fail with the following errors:
```
# golang.org/x/net/http2
../../golang.org/x/net/http2/client_conn_pool.go:305:6: undefined: errors.Is
../../golang.org/x/net/http2/server.go:234:72: undefined: tls.VersionTLS13
```

See [here](https://travis-ci.org/github/container-storage-interface/spec/jobs/770586117) and [here](https://travis-ci.org/github/container-storage-interface/spec/jobs/770584359) for sample failures.

**Comment by gnufied** [comment]
It should be fixed by https://github.com/container-storage-interface/spec/pull/435 when it merges.

**Comment by chrishenzie** [comment]
Fixed, thank you!
