### ISSUE TITLE
Why don't some CSI requests have [parameters] or [secrets]?

### ISSUE THREAD

**Issue by lambdaS-zh** [container-storage-interface/spec#484]
Referring to [secrets requirements](https://github.com/container-storage-interface/spec/blob/master/spec.md#secrets-requirements), secrets MAY be required by plugin to complete a RPC request. My understanding is that all volume operations in one SP context(e.g. StorageClass in k8s) share the same `parameters` or `secrets`, while all snapshot operations share another pack of `parameters` or `secrets`.

So why don't some CSI requests have `parameters` or `secrets`? I found that `NodeUnstageVolumeRequest`, `NodeUnpublishVolumeRequest`, `ListVolumesRequest` and some others don't have the 2 fields. By comparison, all snapshot requests have the field `secrets`.

**Comment by jdef** [comment]
Do you have a use case that is blocked by the current API?

**Comment by lambdaS-zh** [comment]
@jdef not yet. But someone else may meet problems. For example, storage vendors may expect their plugin serves in front of multiple storage backends which have different credentials(#461). This may require all volume operations contain those informations.
I'm confused `CreateVolumeRequest` has those fields while `ListVolumesRequest` does not.
Personally, I just think it's better to keep the same style as those in snapshot.

**Comment by lambdaS-zh** [comment]
@jdef On the other hand, also I'm not sure whether this use case should be supported. Maybe this should be solved by storage backends themselves.

**Comment by jdef** [comment]
For the 3 API calls you mention explicitly, I believe it was intentional to
exclude per volume parameters and/or secrets.

Credentials/parameters needed to access a SP backend API, that are not
volume specific, should be provided at plug-in deploy-time by the operator
and/or process that runs the plug-in itself.

If there is no blocked use case, please close this ticket.

**Comment by lambdaS-zh** [comment]
@jdef By the same logic, is the `secrets` of `ListSnapshotsRequest` snapshot specific?

**Comment by lambdaS-zh** [comment]
@jdef By the same logic, is the `secrets` of `ListSnapshotsRequest` snapshot specific?
