### ISSUE TITLE
Is `Zero` ( size)  allowed on CapacityRange field of  createVolume?  

### ISSUE THREAD

**Issue by humblec** [container-storage-interface/spec#488]
The createVolume capacityRange does not mention whether the `createVolume->CapacityRange` can be `0` or less . Is `zero` size/capacity expected/allowed by the spec? 

```
  // This field is OPTIONAL. This allows the CO to specify the capacity
  // requirement of the volume to be provisioned. If not specified, the
  // Plugin MAY choose an implementation-defined capacity range. If
  // specified it MUST always be honored, even when creating volumes
  // from a source; which MAY force some backends to internally extend
  // the volume after creating it.
  CapacityRange capacity_range = 2;
```

**Comment by humblec** [comment]
Cc @jdef @msau42

**Comment by humblec** [comment]
it looks like its completely left to the CO and from spec side its flexible  .. closing this issue.

**Comment by jdef** [comment]
Flexible sounds like.. room for error. I'll try to look into this soon

**Comment by humblec** [comment]
> Flexible sounds like.. room for error. I'll try to look into this soon

Thanks @jdef , will I keep this issue with `open` state   then?
