### ISSUE TITLE
NodePublishVolume target_path uniqueness requirement

### ISSUE THREAD

**Issue by Jgoldick** [container-storage-interface/spec#49]
There is an assumed uniqueness of target_path across Volumes that today must be enforced by the CO. If two volumes had the same target_path and they ended up on the same node there would be problems, even worse this bad config would be masked if they were first published on different nodes. 

Even if we implemented the changes described in [https://github.com/container-storage-interface/spec/issues/17](url) and [the](https://github.com/container-storage-interface/spec/issues/37) target_path would still need to be unique relative to the container-scoped name space. 

Note for those of a Windows-bent: be aware that not every file system is case sensitive so one can have two different strings that are effectively the same target_path.

**Comment by jdef** [comment]
The CO determines target_path. I think we envisioned that CO's would be
smart enough to not specify overlapping values for target_path such that
multiple vols were published to the same path. Are you saying that CSI
should explicity state this assumption?

**Comment by Jgoldick** [comment]
Yes, I have a general leaning to making assumptions explicit in specs within reason.

While I know there's a background assumption that these paths are probably some form of hash or UUID, that is not necessarily going to be case forever unless it's added as a requirement in this spec.

There's a lot of motivation for human readable strings in practice. Once you allow that, and add in the fact that Windows file names are case-insensitive Unicode, then cluster unique target names are not going to happen without enforcement by the CO.
