### ISSUE TITLE
Proposal: add VolumeSnapshot name & namespace in DeleteSnapshot & ListSnapshot interface.

### ISSUE THREAD

**Issue by mowangdk** [container-storage-interface/spec#492]
we want to use these infos in ListSnapshots & DeleteSnapshot methods for check custom labels in VolumeSnapshots. Is it possible to pass this information like the CreateSnapshot interface?

**Comment by jdef** [comment]
This sounds like a question for k8s sig storage. (name,ns) identifiers are
a k8s api thing. This is not a k8s project.
