### ISSUE TITLE
how does ValidateVolumeCapabilities work

### ISSUE THREAD

**Issue by cn-zhouhj** [container-storage-interface/spec#494]
everything of our project work fine but ValidateVolumeCapabilities, we can create a volume and expend 、clone、snapshot. publish the volume to a pod, and the pod is working correctly. but we can‘t find any evidence shows that **ValidateVolumeCapabilities** has been called.
so can anyone tell us that how to call ValidateVolumeCapabilities. dose it need to deply a sidercar or others.

**Comment by jdef** [comment]
This sounds like a question for k8s SIG Storage.
