### ISSUE TITLE
Question:  If a CSI driver does not advertise the LIST_VOLUMES capability in its ControllerGetCapabilities response and does not implement the ListVolumes method, is the driver still considered CSI 1.6 compliant?

### ISSUE THREAD

**Issue by adarsh-dell** [container-storage-interface/spec#575]
Question:

I have a question regarding CSI compliance, and I know it’s too basic. If a **CSI driver** does **not advertise** the `LIST_VOLUMES` capability in its `ControllerGetCapabilities `response and does not implement the `ListVolumes `method, **is the driver still considered CSI compliant**?
Assuming other mandatory methods (See below) are implemented.

As per my understanding, the `ListVolumes `method must be implemented only if the driver explicitly advertises the `LIST_VOLUMES `capability in its `ControllerGetCapabilities`. Otherwise, it is not mandatory. The same principle applies to other methods as well—they must only be implemented if the driver advertises the corresponding capabilities in  `ControllerGetCapabilities `or in `NodeGetCapabilities`.

Additionally, the following methods must always be implemented for a CSI driver to be compliant, as they do not depend on any specific advertised capabilities:

Mandatory Methods for All CSI Drivers:

**Identity Service:**

`GetPluginInfo`: Provides basic plugin metadata such as name and version.
`GetPluginCapabilities`: Declares the capabilities supported by the driver.
`Probe`: Checks the readiness and health of the plugin.

**Controller Service:**

`ControllerGetCapabilities`: Ensures the CO knows what features the driver supports.
`ValidateVolumeCapabilities`: Checks whether a volume supports the requested capabilities.

**Node Service:**

`NodePublishVolume`: Handles mounting volumes to containers.
`NodeUnpublishVolume`: Handles unmounting volumes from containers.
`NodeGetCapabilities`: Reports node-specific features such as staging.
`NodeGetInfo`: Reports topology information and volume attach limits.

Could you please confirm if my understanding is correct?

Since there are very few must-implement methods that are required unconditionally in each CSI spec, and given that the latest specs introduce methods that can be used only after enabling the Alpha feature, if an organization implements all the mandatory methods and directly adopts the latest CSI spec, would that be sufficient for CSI compliance?

Thanks

**Comment by shanmydell** [comment]
@jdef @jieyu @saad-ali Could you please help us here?

**Comment by anandrajak1** [comment]
@gnufied @pohly @caniszczyk - Please us know for any updates?

**Comment by gnufied** [comment]
Yes, a driver is still CSI compliant if it doesn't implement `LIST_VOLUMES`. It is another matter if certain features in CO depend on this capability and if a driver doesn't implement it, then that particular feature will be broken.

Also github issue may not be the right place to ask questions like these. You are welcome to post them on CSI's mailing list. Please see - https://github.com/container-storage-interface/community

**Comment by adarsh-dell** [comment]
> Yes, a driver is still CSI compliant if it doesn't implement `LIST_VOLUMES`. It is another matter if certain features in CO depend on this capability and if a driver doesn't implement it, then that particular feature will be broken.
> 
> Also github issue may not be the right place to ask questions like these. You are welcome to post them on CSI's mailing list. Please see - https://github.com/container-storage-interface/community
@gnufied As we can see the ListVolumes as a MUST be implemented method in CSI 1.6 spec so can you please clarify it wrt CSI 1.6 spec?

Thanks for the reply. Will follow the above guidelines.

**Comment by gnufied** [comment]
>As we can see the ListVolumes as a MUST be implemented method in CSI 1.6 spec so can you please clarify it wrt CSI 1.6 spec?

Where do you see that `LIST_VOLUMES` *MUST* be implemented? I do not see that at all.

**Comment by adarsh-dell** [comment]
I can see that it MUST be implemented but again condition is there that if driver is advertising this capability.

<img width="955" alt="image" src="https://github.com/user-attachments/assets/678985cd-b994-496e-9dd3-2b8a6c05f67c">

**Comment by anandrajak1** [comment]
@gnufied - Let us know your thoughts on this.

**Comment by gnufied** [comment]
I do not understand. I thought this was self-evident. `ListVolumes` MUST be only implemented if your driver reports `LIST_VOLUMES` capability. A driver is CSI is compliant if it doesn't implement `LIST_VOLUMES` capability and hence does not implement `ListVolumes` RPC call.

**Comment by anandrajak1** [comment]
Ok thank @gnufied for your clarification. Appreciate your help.

**Comment by adarsh-dell** [comment]
> I do not understand. I thought this was self-evident. `ListVolumes` MUST be only implemented if your driver reports `LIST_VOLUMES` capability. A driver is CSI is compliant if it doesn't implement `LIST_VOLUMES` capability and hence does not implement `ListVolumes` RPC call.

Thank you @gnufied.
