### ISSUE TITLE
Remove ListVolumes RPC

### ISSUE THREAD

**Issue by cpuguy83** [container-storage-interface/spec#58]
I would like to propose that we remove the `ListVolumes` RPC.

The case for this RPC, IIRC, is that the CO would like to know what volumes are available. I don't think this is required though and the RPC itself is pretty complex (with [filtering](https://github.com/container-storage-interface/spec/issues/54), pagination). The list itself could become "corrupt" in between page results. 
Generally these can't (or shouldn't) be used as volumes until a `CreateVolume` is called since we'll usually want to store some metadata about the volume in the CO which won't be available for "listed" volumes.

Ideally the CO would keep a list of the volumes it knows about (which happened presumably got there by some request that eventually called `CreateVolume`). In the event of some data lost on the cluster, we can just call `CreateVolume` when needed since this is expected to be idempotent.

Additionally I have some experience with this as I implemented the `List` endpoint for docker volume plugins (for all the same reasons we implemented here), where we basically just end up with a bunch of a volumes and none of our expected metadata, and it ends up in a weird experience. I would actually like to phase out this call in Docker at some point.

**Comment by jieyu** [comment]
> In the event of some data lost on the cluster, we can just call CreateVolume when needed since this is expected to be idempotent.

How do we find out the `name` and `parameters` for the `CreateVolumeRequest` in that case?

`ListVolumes` is *optional*. Neither CO or SP is forced to implement this. I think we'll end up with some experimental features that we're going to experiment with. If we can find a good way to allow CO/SP to experiment new APIs without forking the spec, I am all for making it experimental.

**Comment by cpuguy83** [comment]
> How do we find out the name and parameters for the CreateVolumeRequest in that case?

Wouldn't the backend reject the create request if the params don't match?

**Comment by jieyu** [comment]
@cpuguy83 In the case CO loses metadata (or crashes, and wants to do a reconciliation), this interface allows the CO to get all the known volumes from the SP. The CO don't have a list of volume names to call `CreateVolumeRequest`. Obviously, we cannot enumerate all volume names and parameters, and rely on rejection to tell the existence of a volume.

**Comment by gpaul** [comment]
This likely supports the use case where external volumes are detached from one cluster and attached to another, too.

**Comment by cpuguy83** [comment]
I guess I'm fine as long as it's optional. However, it seems like it is a bit difficult to use volumes listed from the plugin directly (no user interaction) since there will be none of the CO metadata associated with it available.

**Comment by julian-hj** [comment]
+1 for removing this api from the first revision of the spec (and apologies if y'all discussed it in the last WG meeting and I missed it.  I was away.) From the Cloud Foundry perspective, we will not use this API any time soon, so it feels like something we could consider to add later unless it will block important Mesos use cases in the v1 time frame.

**Comment by saad-ali** [comment]
It is optional, will leave it as such.
