### ISSUE TITLE
Add CSI logo

### ISSUE THREAD

**Issue by caniszczyk** [container-storage-interface/spec#67]
Here are the CSI logo artifacts (vector formats included).

I recommend creating an "artwork" or "logo" repo in the CSI github organization and putting them there. The community repo could be a good place too.

**Comment by caniszczyk** [comment]
[CSI.zip](https://github.com/container-storage-interface/spec/files/1177629/CSI.zip)

**Comment by jieyu** [comment]
This is merged in #66
