### ISSUE TITLE
Concurrency Ownership

### ISSUE THREAD

**Issue by akutz** [container-storage-interface/spec#70]
This section of the specification is troubling to me:

> In general the Cluster Orchestrator (CO) is responsible for ensuring that there is no more than one call “in-flight” per volume at a given time. However, in some circumstances, the CO may lose state (for example when the CO crashes and restarts), and may issue multiple calls simultaneously for the same volume. The plugin should handle this as gracefully as possible.

Concurrency is binary -- either the CO always owns concurrency with regards to in-flight volume operations or it never does. For example, if a plug-in has to "gracefully" handle a situation where a CO loses state then a plug-in has to *always* assume that scenario is occurring since the CO doesn't indicate to its plug-ins that state has been lost (or if it does it is not part of this specification).

For example, because of the proposed manner in which Node plug-ins should handle `NodePublishVolume` messages (mount all volumes into a private directory and bind mount them to the message's `TargetPath`), concurrency is paramount. If a `NodePublishVolume` message is received slightly before a `NodeUnpublishVolume` the plug-in would need to effectively synchronize itself on all public methods of ingress. Otherwise the `NodeUnpublishVolume` operation could complete first causing the `NodePublishVolume` operation to error, or worse, leave the underlying host in a fail state.

All this is moot if the CO takes ownership of concurrency, but as stated above, this is a binary ownership -- either the CO *always* ensures there's only one in-flight operation per volume or a plug-in has to assume the CO *never* ensures there's only one in-flight operation per volume.

I propose the specification either identify that the CO *must* own concurrency or relocate that burden into the plug-in so that authors can develop their plug-ins accordingly.

**Comment by jdef** [comment]
#104

**Comment by jsafrane** [comment]
I wonder how CO could ever ensure that there's only one in-flight operation per volume.

CO initiates an operation (say `ControllerPublishVolume`) over a socket (e.g. TCP). Then it crashes and restarts. CO *could* remember that there was an operation in progress, but it does not have any clue if it has finished or not and if the volume is attached or not - it does not have the TCP socket to check for a response.

I am afraid that it's up to the plugin to handle that.

**Comment by jdef** [comment]
I think we said that the CO will take a *best effort* approach to avoiding overlapping ops for the same volume. Robust plugins should probably code defensively against overlapping operations (or else delegate that responsibility to some backend component).

**Comment by saad-ali** [comment]
You are correct, a well designed plugin should handle concurrency.

But ultimately it should be the decision of the plugin author. And we should not word the spec to impose it as a requirement on the plugin. If someone wants to implement a simple plugin and accept the risk of inconsistency the spec should not block that. Therefore, the current wording seems fine.
