### ISSUE TITLE
spec: Tag a 0.1.0-rc1 or alpha release

### ISSUE THREAD

**Issue by akutz** [container-storage-interface/spec#81]
Would it be appropriate to go ahead and create and publish an annotated tag of this repository in order for others to consume some version via standard workflows that work with tags?

**Comment by jdef** [comment]
yes. @jieyu will create a milestone for this and we'll assign blocking issues to it

**Comment by jdef** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/container-storage-interface-community/e7mjWOhemd8/EJl9FUsZAQAJ

closing this out since voting has started
