### ISSUE TITLE
Allow SP to specify architecture capabilities?

### ISSUE THREAD

**Issue by codenrhoden** [container-storage-interface/spec#86]
Would it be appropriate for part of a `PluginInfoResponse` to specify whether a centralized controller deployment is supported? When I think of the different [scenarios](https://github.com/container-storage-interface/spec/blob/master/spec.md#architecture) in the spec, there are SPs that are only going to work in headless fashion (whether as separate endpoints on the same node, or a combined endpoint).

I'm thinking about plugins for local block storage, using pre-existing NFS shares, etc. In these scenarios, a remote/centralized controller plug-in has nothing to offer (it can't create/delete, it can't attach/detach, it can't list volumes), so it would be beneficial to dictate that the SP can only be run in a not-centralized fashion.

Of course, it's also possible to just run the centralized controller have it advertise none of the optional RPCs, which makes it mostly a no-op. I think in some ways this is related to ListVolumes (#58) and whether that RPC is at all useful. If that is an RPC that we want to be still be useful when an SP works only with local devices, we would want to enforce that a centralized controller isn't possible for some SPs.

Thoughts?

**Comment by akutz** [comment]
Hi @codenrhoden,

I think this is a very good idea. We've encountered similar issues with supporting centralized/decentralized deployments of specific platforms. Users expect all platforms should support the same configuration, but this is simply not the case. Allowing a CO to inform the user via its UX that a specific plug-in (platform) does not support the current configuration would be a very helpful thing indeed.

**Comment by jdef** [comment]
I remember the WG discussing `CSI_MODE` at some point, though it was backwards from what's being described here: the CO would declare the intended the mode of operation of a plugin binary by setting an envvar and the Plugin would fail to start (with some appropriate error code/message) if the deployment mode was unsupported. That approach was eschewed on the basis that CSI should focus on protocol and not deployment concerns. Largely due to the fact that deployment is specifically listed as a non-goal of the MVP (v1) for CSI. So we narrowed down the runtime interface to a single envvar `CSI_ENDPOINT`.

That said, I could probably get behind a `GetPluginInfoResponse` reply field that indicates which gRPC services are available for the running plugin instance, in order to allow a CO to reason about whether it's been configured properly (or not). Or .. goes gRPC already provide this capability in-band?

I'm leery of indicating specific deployment architectures via the CSI API for the v1 spec.

**Comment by akutz** [comment]
> CSI should focus on protocol and not deployment concerns. 

Except the first part of the CSI spec details the exact three, proposed deployment models. It's literally almost the first concern of the specification.

**Comment by jdef** [comment]
Yes, @akutz, the first part of the spec talks about deployment models that a CO **should** consider. This was added to give context w/ respect to how we envisioned CSI plugins being used across CO's. It was specifically **not** intended to be a closed set of supported deployment architectures. If that's not clear then we should probably clean up the wording.

**Comment by codenrhoden** [comment]
Thanks for the background, @jdef. 

I almost asked this in my original description, but rephrasing things a bit, would it be considered antithetical to CSI to design an SP that *only* works in a headless fashion? Without some change to the v1 spec (which seems unlikely to happen) there does not appear to be a way to convey to the CO (or have the CO assert) a mode of deployment. I could certainly develop a plugin that only works headless, and document that that's how you need to use it, but I worry about user experience in that scenario. I also wonder if it would preclude a CO from being compatible with a plugin (for example, what if k8s only works with plugins that are centralized?).

I'd rather deploy a centralized controller plugin that is a big no-op than force a headless deployment if it's the difference between a plugin being usable by a CO, even though the capabilities of that plugin are greatly diminished (e.g. no ability to `ListVolumes`).

I'm currently developing a couple alpha/prototype plugins for NFS and local block devices, so that's why this is on my mind.

**Comment by akutz** [comment]
Hi @jdef,

I share @codenrhoden's concern, and I'd like to restate it slightly with a focus on the initial adoption of CSI. I'm concerned that without the spec both suggesting AND requiring deployment requirements that CSI will be immediately fragmented by plug-ins that only support a subset of possible deployment strategies used by COs.

**Comment by codenrhoden** [comment]
I had one more thought here, that may serve as a compromise.

Remember that my perspective in asking this question is building plugins that target local-only actions. Think of a hypothetical LVM driver -- a centralized controller can't do anything in that case -- no create/delete, no list, etc.  However, if the controller **is** running on a node where a node plugin is running, it **can** do those things...

In the spirit of `CSI_MODE`, which was deemed out of scope for v1, would anything preclude me from handling this at a plugin config level? I could explicitly tell a plugin, via env config, to run in a "local controller" mode. I don't think this breaks anything with regards to the spec, because the plugin wouldn't be "assuming" that it's running on the same node as a node plugin if we explicitly *tell it* that it is.

I don't necessarily see a reliable way to detect the scenario programmatically, as you could run the controller plugin and the node plugin as different processes in different containers if you wished. Besides, even if you could detect that you we running co-resident to a node plugin, that doesn't necessarily mean that controller service is meant to be local only. While it's not in the architecture diagram, you could deploy a identity+node+controller service on a single node, while still intending for that controller service to be a centralized version of the deployment.

I guess I'm just trying to suss out how much flexibility there is when it comes to plugin configuration and centralized vs headless deployments.

**Comment by jdef** [comment]
A plugin distribution is expected to satisfy at least one deployment architecture (whether or not its illustrated as a possibility in the CSI spec). The CSI spec illustrates the options that we think are **most likely** to be common. It's very likely that there are useful deployment options that we **haven't** listed (see the example, after the following list). A plugin distribution does not need to support more than one type of deployment. Some examples we had in mind for deployment (keeping in mind that any CSI plugin endpoint presents an Identity service in addition to at least one other CSI service):

1. LVM CSI plugin --> headless deployment: every agent node in the cluster runs a plugin that presents both Controller and Node services via the same endpoint
1. EBS CSI plugin --> split w/ Controller service on master hosts, Node service on agent hosts
1. SAN CSI plugin --> split w/ Controller service on master hosts that LB's CSI gRPC operations to an external control unit; Node service on agent hosts.

I guess I could see problems in the case where a plugin distribution wanted (a) some Controller RPCs running on master hosts; (b) some (remainder of) Controller RPCs + all Node RPCs running on agent hosts. Each plugin instance reports its capabilities, so it's still discoverable by the CO but I don't think the CSI WG considered this particular scenario, and it would seem to complicate CO configuration. Is this type of deployment useful? My gut says no, but maybe someone, somewhere has a use case for this? @akutz is this an example of the fragmentation that you're worried about?

@codenrhoden Nothing precludes you from handling mode selection at a config level, it's just not part of the CSI spec itself. It's certainly possible for plugins to have their own environment variables and/or command line flags to configure specific behavior. It's completely reasonable for a multi-modal plugin to offer a configuration option that "flips on" specific CSI services. It's up to the (operator-configured) plugin supervisor (which may or may not be the CO) to establish the runtime environment for a plugin process.

HTH

**Comment by codenrhoden** [comment]
@jdef Yes, that helps immensely! I had been incorrectly thinking that a plugin needed to be capable of satisfying all deployment architectures, even if it meant diminished functionality. The ability for a plugin distribution to dictate how it should be deployed (via documentation and config options for now, not the spec or RPCs) means the plugin can be developed in the way to provide the most capability. That seems like an obvious desired trait when I write it out, but I hadn't taken that to be the case.

Unless this needs to be a placeholder for a future enhancement re: `CSI_MODE`, or a Capabilities extension for plugin architecture modes, I think this can be closed (I'd close it myself, but at least want to see if there is a desire to hold onto it for future work. I expect it will just be closed).

**Comment by jdef** [comment]
Closing this out, we can re-open if it becomes part of the CSI charter.
