### ISSUE TITLE
Add size limits to calls where arbitrary amount of data can be passed in

### ISSUE THREAD

**Issue by saad-ali** [container-storage-interface/spec#87]
https://github.com/container-storage-interface/spec/pull/83#discussion_r133594577 adds a limit of 1 MB for credential data. We should consider something similar for other areas in the interface where an arbitrary amount of data can be passed in. It's always easier to start with a restriction and loosen it later then start with no limit and try to impose it later.

**Comment by jdef** [comment]
field size limits were added here: https://github.com/container-storage-interface/spec/blob/master/spec.md#field-size-limits

please re-open this if needed
