### ISSUE TITLE
spec: Result language MUST change

### ISSUE THREAD

**Issue by akutz** [container-storage-interface/spec#89]
I discovered an problem in the spec's language that becomes an unintended bug in Go code. For example:

```proto
message DeleteVolumeResponse {
  message Result {}

  // One of the following fields MUST be specified.
  oneof reply {
    Result result = 1;
    Error error = 2;
  }
}
```

The spec clearly states a `Result` or `Error` **MUST** be specified. However, the code Go generates means a `type DeleteVolumeResponse_Result struct` has no fields (as it shouldn't given the above spec). The problem is Go tries to be efficient. The code generated by `protoc` for Go creates a `DeleteVolumeResponse` with no way to **set** a `DeleteVolumeResponse_Result` as such an object would **never** have **any data**.

The problem is with reply validation. Because using the language of the specification the following should never panic:

```go
if reply.GetError() == nil && reply.GetResult() == nil {
	panic("reply has nil error and result")
}
```

The following RPCs are affected:

1. `DeleteVolume`
2. `ControllerUnpublishVolume`
3. `NodePublishVolume`
4. `NodeUnpublishVolume`
5. `ProbeNode`

Successful responses from the above calls will all return a `nil` value for both `GetError` and `GetResult` -- a violation of the specification's language.

I'm open to suggestions here. I have considered the following:

1. Change the specification's comments to reflect the nature of possible issues related to generated code.
2. Omit the `Result` field from the affected responses altogether. I'm not sure I like this as it means the five responses are anti-pattern from the rest of the RPC response messages.
3. Change the `Result` field of the affected responses to a string value so that it is always possible to set a value, even if it is empty.

Thoughts?

I'm leaning towards the first option, but I **do** want to see a change made. Otherwise the language of the specification is in opposition to how the specification is implemented by standard tools, such as `protoc`.

**Comment by akutz** [comment]
Nevermind, I'm an idiot. I missed setting the result via the reply on the server using the empty struct that adheres to the result interface. That's why it was nil. I thought Go was just optimizing it out.

Still, I suppose I'm not entirely off-base as the discussion is still somewhat valid. We're sending an empty struct to satisfy the language of *MUST contain one of the following* when the result is always empty when successful. Would it be worth having an implied successful result by the absence of an error rather than the presence of a nil result AND nil error?

**Comment by akutz** [comment]
FWIW, this is what a valid response looks like when using Go to create it:

```go
	return &csi.DeleteVolumeResponse{
		Reply: &csi.DeleteVolumeResponse_Result_{
			Result: &csi.DeleteVolumeResponse_Result{},
		},
	}, nil
```

See my point? A valid response could omit the empty structs altogether and save on both transport cost (of marshaling) and size.

**Comment by akutz** [comment]
Still, I think it's more valuable for all the RPCs to have a similar functional pattern than optimizing out some fairly low cost operations such as marshalling empty structs.

**Comment by jdef** [comment]
Thanks for bringing this up. FWIW I'm in favor of consistency: the RPCs
should "have a similar functional pattern". I don't see a ton of value in
optimizing away empty structs.
