### ISSUE TITLE
spec: This field is REQUIRED

### ISSUE THREAD

**Issue by akutz** [container-storage-interface/spec#90]
I have a question regarding REQUIRED fields, for example:

```proto
  // The capabilities that the provisioned volume MUST have: the Plugin
  // MUST provision a volume that could satisfy ALL of the
  // capabilities specified in this list. The Plugin MUST assume that
  // the CO MAY use the  provisioned volume later with ANY of the
  // capabilities specified in this list. This also enables the CO to do
  // early validation: if ANY of the specified volume capabilities are
  // not supported by the Plugin, the call SHALL fail. This field is
  // REQUIRED.
  repeated VolumeCapability volume_capabilities = 4;
```

The field must be non-nil, but what if the the array has no elements? Does a zero-length array still meet the intent of REQUIRED? It's important as it affects the way that message validation is handled.

**Comment by jdef** [comment]
I believe that the intent for a REQUIRED array/map field is that the array/map is NOT empty.
@jieyu please correct me if I'm wrong

**Comment by akutz** [comment]
Hi @jdef,

That's a fair point, and honestly, for some fields that's evident. For example, for `VolumeID` I can validate:

* `VolumeID != nil`
* `VolumeID.Values != nil`
* `len(VolumeID.Values) > 0`

(of course Go will perform a valid `len` check against a nil value so the second check above isn't necessary for Go, but is for other languages so I left it in the example)

The above is implicit as a VolumeID with no values is pointless. An empty Capability array may be perfectly valid, however, as it could imply no requirements on the volume. In other words -- any volume type will do.

**Comment by gpaul** [comment]
Bump

I am proceeding under the assumption that 'Capability' is different from 'Requirement'. That is, an empty VolumeCapability list implies a volume with No capability, not one with Any capability.

**Comment by jdef** [comment]
@jieyu we went back and forth on the wording for this. I believe your intent is that REQUIRED means that this repeated field SHALL NOT be empty. Please confirm.

**Comment by gpaul** [comment]
Bump?
