### ISSUE TITLE
doc: clarify process for modifying protobufs in the spec

### ISSUE THREAD

**Issue by jdef** [container-storage-interface/spec#94]
The current process is to modify the `spec.md` file and then regenerate the .proto file. This isn't clear at first glance from the README or the CONTRIBUTING page. The CONTRIBUTING page reminds one to rebuild after making changes, but it's a vague instruction.

**Comment by akutz** [comment]
Hmm, I don't know. It tells one what to do exactly. Just run "make". That wasn't followed in the case to which you refer, despite the person being instructed to do so multiple times.

**Comment by jdef** [comment]
It says this:
> Prior to committing code please run make in order to update the protobuf file and any language bindings

... which *implies* that the change you're making is to a file other than the protobuf / language-bindings. The point of this ticket is that the instructions should be more explicit w/ respect *where* proto changes should be originally introduced: the `spec.md` file

**Comment by akutz** [comment]
Hi @jdef,

Good catch! I'm sorry I wasn't more clear originally.
